# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
- package-ecosystem: npm
  directory: /src/nerdbank-streams
  schedule:
    interval: monthly
- package-ecosystem: nuget
  directory: /
  schedule:
    interval: weekly
  ignore:
  - dependency-name: Microsoft.Bcl.AsyncInterfaces # We want to match the minimum target .NET runtime
