[package]
name = "nerdbank-streams"
version = "0.1.0"
edition = "2021"
rust-version = "1.81"

[dependencies]
async-trait = "0.1.82"
bytes = "1.8.0"
msgpack_simple = "1.0.2"
rmp = "0.8"
tokio = { version = "1", features = ["full"] }
