[package]
name = "nerdbank-streams"
version = "0.1.0"
edition = "2021"
rust-version = "1.81"

[dependencies]
async-trait = "0.1.82"
msgpack_simple = "1.0.2"
tokio = { version = "1", features = ["full"] }
