name: 🏭 Build

on:
  push:
    branches:
    - main
    - 'v*.*'
    - validate/*
  pull_request:
  merge_group:
  workflow_dispatch:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  BUILDCONFIGURATION: Release
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages/

jobs:
  build:
    name: 🏭 Build

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
        - os: ubuntu-24.04
          rid: linux
        - os: macOS-15
          rid: osx
        - os: windows-2025
          rid: win

    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
        submodules: true
    - name: ⚙ Install prerequisites
      run: |
        ./init.ps1 -UpgradePrerequisites
        dotnet --info

        # Print mono version if it is present.
        if (Get-Command mono -ErrorAction SilentlyContinue) {
          mono --version
        }
      shell: pwsh
    - name: ⚙️ Set pipeline variables based on source
      run: tools/variables/_define.ps1
      shell: pwsh
    - name: 🛠 dotnet build
      run: dotnet build -t:build,pack --no-restore -c ${{ env.BUILDCONFIGURATION }} -warnAsError -warnNotAsError:NU1901,NU1902,NU1903,NU1904 /bl:"${{ runner.temp }}/_artifacts/build_logs/build.binlog"
    - name: 🧪 dotnet test
      run: tools/dotnet-test-cloud.ps1 -Configuration ${{ env.BUILDCONFIGURATION }} -Agent ${{ runner.os }}
      shell: pwsh
    - name: 🧪 NativeAOT test
      run: dotnet publish -c Release -r ${{ matrix.rid }}-x64 -warnaserror
      working-directory: test/NativeAOTCompatibility

    - name: ⚙️ Use Node.js 20.x
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        node-version: 20.x
    - name: ⚙️ yarn
      run: |
        npm install -g yarn@1.x
        yarn install
      working-directory: src/nerdbank-streams
    - name: 🛠️ yarn build
      run: yarn build
      working-directory: src/nerdbank-streams
    - name: 🧪 yarn test
      run: yarn test
      working-directory: src/nerdbank-streams
    - name: 🧪 yarn lint
      run: yarn lint
      working-directory: src/nerdbank-streams

    - name: 💅🏻 Verify formatted code
      run: dotnet format --verify-no-changes --no-restore
      shell: pwsh
      if: runner.os == 'Linux'
    - name: 📚 Verify docfx build
      run: dotnet docfx docfx/docfx.json --warningsAsErrors --disableGitFeatures
      if: runner.os == 'Linux'
    - name: ⚙ Update pipeline variables based on build outputs
      run: tools/variables/_define.ps1
      shell: pwsh
    - name: 📢 Publish artifacts
      uses: ./.github/actions/publish-artifacts
      if: cancelled() == false
    - name: 📢 Publish code coverage results to codecov.io
      run: |
        if ('${{ secrets.CODECOV_TOKEN }}') {
          ./tools/publish-CodeCov.ps1 -CodeCovToken '${{ secrets.CODECOV_TOKEN }}' -PathToCodeCoverage "${{ runner.temp }}/_artifacts/coverageResults" -Name "${{ runner.os }} Coverage Results" -Flags "${{ runner.os }}"
        }
      shell: pwsh
      timeout-minutes: 3
      continue-on-error: true

  docs:
    name: 📃 Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - name: 🔗 Markup Link Checker (mlc)
      uses: becheran/mlc@7ec24825cefe0c9c8c6bac48430e1f69e3ec356e # v1.2.0
      with:
        args: --do-not-warn-for-redirect-to https://learn.microsoft.com*,https://dotnet.microsoft.com/*,https://dev.azure.com/*,https://app.codecov.io/*,https://dotnetfoundation.org/*,https://docs.github.com/* -i https://www.npmjs.com/package/*,https://get.dot.net/ -p docfx,ext
